import "dotenv/config";
import { HumanMessage } from "@langchain/core/messages";
import { ChatMistralAI } from "@langchain/mistralai";
import { searchFriendContextLangChainTool } from "../ai/tools/searchFriendContext.tool.js";

const validFriendId = "5da77ede-2290-4ede-9839-d83a29a310e6";

async function main(): Promise<void> {
    const model = new ChatMistralAI({
        model: "mistral-small-latest",
        temperature: 0,
    });

    const modelWithTools = model.bindTools([
        searchFriendContextLangChainTool,
    ]);

    const userMessage = new HumanMessage(
        `Search the stored relationship history for friend ${validFriendId}
        for information about apologising after a misunderstood or badly
        worded message. Return no more than three results.`,
    );

    // Step 1: Ask the model whether it wants to call a tool.
    const modelResponse = await modelWithTools.invoke([userMessage]);

    console.log("Requested tool calls:");
    console.dir(modelResponse.tool_calls, { depth: null });

    const toolCall = modelResponse.tool_calls?.[0];

    if (!toolCall) {
        throw new Error("The model did not request a tool call");
    }

    if (toolCall.name !== searchFriendContextLangChainTool.name) {
        throw new Error(`Unknown tool requested: ${toolCall.name}`);
    }

    // Step 2: Execute the tool call generated by the model.
    const toolResult =
        await searchFriendContextLangChainTool.invoke(toolCall);

    console.log("\nTool result:");
    console.dir(toolResult, { depth: null });

    // Step 3: Give the tool result back to the model.
    const finalResponse = await modelWithTools.invoke([
        userMessage,
        modelResponse,
        toolResult,
    ]);

    console.log("\nFinal model response:");
    console.log(finalResponse.text);
}

main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
});