name: CI

on:
  push: 
  pull_request: # Trigger on pull requests

jobs:
  test: #create a job called test and run it on a linux machine 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository #download repository code into github runner
        uses: actions/checkout@v4
      - name: Set up Node.js #set up node environment
        uses: actions/setup-node@v4
        with:
          node-version: 25 
          cache: npm #cache npm dependencies to speed up future runs
      - name: Install dependencies #install npm dependencies
        run: npm ci # execute the shell command "npm ci" to install dependencies inside the github runner
      - name: Generate Prisma client #generate the Prisma client
        run: npx prisma generate # execute the shell command "npx prisma generate" to generate the Prisma client inside the github runner
        env:
            DATABASE_URL: postgresql://user:password@localhost:5432/testdb
        
      - name: Run lint #run linter
        run: npm run lint # execute the shell command "npm run lint" to run the linter inside the github runner  
      - name: Run tests #run tests
        run: npm test # execute the shell command "npm test" to run tests inside the
      
      - name: Run build #run build
        run: npm run build # execute the shell command "npm run build" to build the project inside the github runner